"use client";
import {useEffect,useState,type FormEvent} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Checkbox} from "@/components/ui/checkbox";
import {Toaster} from "@/components/ui/sonner";
import {toast} from "sonner";
import {Dashboard} from "@/components/dashboard";
import {MerchantRegistration} from "@/components/registration";
import {LandingStory} from "@/components/landing-story";
import {LoginHeadline} from "@/components/login-headline";
import {LoginVideo} from "@/components/login-video";
import {TerminalManagement} from "@/components/terminal-management";
import {MerchantList} from "@/components/merchant-list";
import {Submissions} from "@/components/submissions";
import {Profile} from "@/components/profile";
import {Operations} from "@/components/operations";
type Screen="login"|"forgot"|"sent"|"new-password"|"success"|"dashboard"|"registration"|"tickets"|"inventory"|"monitoring"|"merchants"|"requests"|"checker"|"signer"|"fees"|"reconciliation"|"settlements"|"ota"|"fraud"|"profile";
const screens:Screen[]=["login","forgot","sent","new-password","success","dashboard","registration","tickets","inventory","monitoring","merchants","requests","checker","signer","fees","reconciliation","settlements","ota","fraud","profile"];
function Logo(){return <img src="/assets/logo.png" width={101} height={36} alt="MAMS" className="logo"/>}
function PasswordField({id,label,value,onChange,autoComplete="new-password",placeholder="Masukan password",error=false}:{id:string;label:string;value:string;onChange:(v:string)=>void;autoComplete?:string;placeholder?:string;error?:boolean}){const [visible,setVisible]=useState(false);return <div className="field"><label htmlFor={id}>{label}</label><div className={`input-wrap ${error?"invalid":""}`}><img src="/assets/lock.png" width={20} height={20} alt=""/><Input id={id} type={visible?"text":"password"} value={value} onChange={e=>onChange(e.target.value)} required autoComplete={autoComplete} placeholder={placeholder} aria-invalid={error}/><button type="button" className="eye" aria-label={visible?"Sembunyikan password":"Tampilkan password"} aria-pressed={visible} onClick={()=>setVisible(!visible)}><img src={autoComplete==="current-password"&&!visible?"/assets/eye-off.png":"/assets/eye.png"} width={20} height={20} alt=""/></button></div></div>}
export default function Home(){
const [screen,setScreen]=useState<Screen>("login"),[email,setEmail]=useState(""),[resetEmail,setResetEmail]=useState(""),[password,setPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirm,setConfirm]=useState(""),[remember,setRemember]=useState(true),[error,setError]=useState(""),[help,setHelp]=useState(false);
useEffect(()=>{window.scrollTo({top:0,left:0,behavior:"instant"})},[screen]);
const [demoAccount,setDemoAccount]=useState<{email:string;password:string}|null>(null);
const rules=[newPassword.length>=8,/[A-Z]/.test(newPassword),/[^A-Za-z0-9\s]/.test(newPassword),/[0-9]/.test(newPassword)];
const labels=["Minimal terdapat 8 karakter","Minimal terdapat satu huruf kapital","Minimal terdapat satu karakter spesial (cth : !@#$%^&*)","Minimal terdapat satu angka"];
useEffect(()=>{const sync=()=>{const s=location.hash.slice(1) as Screen;setScreen(screens.includes(s)?s:"login");setError("")};sync();window.addEventListener("hashchange",sync);try{const e=localStorage.getItem("mams-remembered-email");if(e)setEmail(e)}catch{}return()=>window.removeEventListener("hashchange",sync)},[]);
function go(s:Screen){setError("");setScreen(s);location.hash=s}
function login(e:FormEvent){e.preventDefault();if(demoAccount&&email.trim().toLowerCase()===demoAccount.email&&password!==demoAccount.password){setError("Password tidak sesuai. Gunakan password baru yang sudah dibuat.");return}try{if(remember)localStorage.setItem("mams-remembered-email",email.trim());else localStorage.removeItem("mams-remembered-email")}catch{}try{const previous=sessionStorage.getItem("mams-login-email");if(previous&&previous!==email.trim())sessionStorage.removeItem("mams-profile");sessionStorage.setItem("mams-login-email",email.trim())}catch{}setError("");setPassword("");go("dashboard")}
function save(e:FormEvent){e.preventDefault();if(!rules.every(Boolean)){setError("Password belum memenuhi semua persyaratan.");return}if(newPassword!==confirm){setError("Ulangi password harus sama dengan password baru.");return}setDemoAccount({email:resetEmail.trim().toLowerCase(),password:newPassword});setEmail(resetEmail.trim());setPassword("");setNewPassword("");setConfirm("");go("success")}
if(screen==="profile")return <><Toaster theme="light" position="top-center"/><Profile onDashboard={()=>go("dashboard")} onRegister={()=>go("registration")} onLogout={()=>go("login")}/></>;
if(screen==="dashboard")return <><Toaster theme="light" position="top-center"/><Dashboard onRegister={()=>go("registration")} onLogout={()=>{setPassword("");go("login")}}/></>;
if(screen==="registration")return <><Toaster theme="light" position="top-center"/><MerchantRegistration onDashboard={()=>go("dashboard")} onLogout={()=>{setPassword("");go("login")}}/></>;
if(screen==="tickets"||screen==="inventory"||screen==="monitoring")return <><Toaster theme="light" position="top-center"/><TerminalManagement page={screen} onDashboard={()=>go("dashboard")} onRegister={()=>go("registration")} onLogout={()=>go("login")}/></>;
if(screen==="requests"||screen==="checker"||screen==="signer")return <><Toaster theme="light" position="top-center"/><Submissions page={screen} onDashboard={()=>go("dashboard")} onRegister={()=>go("registration")} onLogout={()=>go("login")}/></>;
if(screen==="fees"||screen==="reconciliation"||screen==="settlements"||screen==="ota"||screen==="fraud")return <><Toaster theme="light" position="top-center"/><Operations page={screen} onDashboard={()=>go("dashboard")} onRegister={()=>go("registration")} onLogout={()=>go("login")}/></>;
if(screen==="merchants")return <><Toaster theme="light" position="top-center"/><MerchantList onDashboard={()=>go("dashboard")} onRegister={()=>go("registration")} onLogout={()=>go("login")}/></>;
const errorMessage=error?<p className="error" role="alert">{error}</p>:null;
return <><Toaster theme="light" position="top-center"/>{screen==="login"?<main className="mams-landing"><section id="mams-login-hero" className="login-page mams-glass-login" aria-label="Login MAMS"><LoginVideo/><div className="landing-hero-logo"><Logo/></div><p className="landing-hero-powered">Powered By PT.Solusi Pembayaran Elektronik</p><div className="landing-login-stack"><LoginHeadline/><section className="login-side"><form className="login-form" onSubmit={login}><div className="welcome"><h2>Welcome Back</h2></div><div className="login-fields"><div className="field"><label htmlFor="login-email">Email</label><div className="input-wrap"><Input id="login-email" type="email" required autoComplete="username" placeholder="yourname@mail.com" value={email} onChange={e=>setEmail(e.target.value)}/></div></div><PasswordField id="login-password" label="Password" value={password} onChange={setPassword} autoComplete="current-password" placeholder="yourname@mail.com" error={Boolean(error)}/><div className="options"><label className="remember" htmlFor="remember"><Checkbox id="remember" checked={remember} onCheckedChange={v=>setRemember(v===true)} className="remember-checkbox"/><span>Remember Me</span></label><button type="button" className="text-link" onClick={()=>{setResetEmail(email);go("forgot")}}>Lupa Password</button></div>{errorMessage}<div className="login-actions"><Button type="submit" className="primary">Login</Button><Button type="button" variant="outline" className="outline" onClick={()=>toast.info("Pendaftaran belum tersedia",{description:"Demo tahap ini mencakup login dan reset password."})}>Daftar</Button></div></div></form></section></div><button className="landing-scroll-cue" type="button" onClick={()=>document.getElementById("mams-about")?.scrollIntoView({behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"})}>Scroll untuk mengenal MAMS<span aria-hidden="true">⌄</span></button></section><LandingStory/></main>:<main className="reset-page"><header className="reset-header"><Logo/><h1>Reset Password</h1><div/></header><section className="reset-stage" aria-labelledby="reset-title" key={screen}>
{screen==="forgot"&&<form className="reset-card forgot-card" onSubmit={e=>{e.preventDefault();go("sent")}}><img className="spot" src="/assets/password.png" width={75} height={75} alt=""/><div className="card-copy"><h2 id="reset-title">Lupa Password Anda ?</h2><p>Untuk melakukan reset password silahkan masukan email anda yang terdaftar di MAMS<br/>Lalu kami akan mengirimkan link Instruksi reset password ke email anda</p></div><div className="field"><label htmlFor="reset-email">Masukan Email</label><div className="input-wrap"><img src="/assets/email.png" width={20} height={20} alt=""/><Input id="reset-email" type="email" required autoComplete="email" value={resetEmail} onChange={e=>setResetEmail(e.target.value)} placeholder="Mail.com"/></div></div><div className="button-row"><Button type="button" variant="outline" className="outline" onClick={()=>go("login")}>Batal</Button><Button type="submit" className="primary">OK</Button></div></form>}
{screen==="sent"&&<section className="reset-card result-card"><div className="result-spot"><img className="spot" src="/assets/mail.png" width={75} height={75} alt=""/></div><div className="card-copy"><h2 id="reset-title">Email Telah Terkirim</h2><p>Link reset password telah dikirim ke email anda mohon membuka email anda dan ikuti instruksi selanjutnya</p></div><Button className="primary small" onClick={()=>{setNewPassword("");setConfirm("");go("new-password")}}>OK</Button></section>}
{screen==="new-password"&&<form className="reset-card password-card" onSubmit={save}><img className="spot" src="/assets/password.png" width={75} height={75} alt=""/><h2 id="reset-title">Masukan Password Baru</h2><div className="password-fields"><PasswordField id="new-password" label="Masukan Password Baru" value={newPassword} onChange={setNewPassword}/><PasswordField id="confirm-password" label="Ulangi Password Baru" value={confirm} onChange={setConfirm} error={Boolean(error)&&newPassword!==confirm}/></div><ul className="requirements" aria-label="Persyaratan password">{labels.map((label,i)=><li key={label} className={rules[i]?"met":newPassword?"unmet":"pending"}><img className="requirement-asset" src={rules[i]?"/assets/requirement-met.png":newPassword?"/assets/requirement-unmet.png":"/assets/requirement-empty.png"} width={24} height={24} alt=""/><span>{label}</span><span className="sr-only">{rules[i]?": terpenuhi":": belum terpenuhi"}</span></li>)}</ul>{errorMessage}<Button type="submit" className="primary small">Simpan</Button></form>}
{screen==="success"&&<section className="reset-card result-card"><div className="result-spot"><img className="spot" src="/assets/success.png" width={75} height={75} alt=""/></div><div className="card-copy"><h2 id="reset-title">Password Berhasil Diubah</h2><p>Silahkan login dengan password baru yang ada buat</p></div><Button className="primary small" onClick={()=>go("login")}>Login</Button></section>}
</section></main>}<div className="demo-guide"><button type="button" aria-expanded={help} onClick={()=>setHelp(!help)}>Mode demo{help?" · Tutup":" · Panduan"}</button>{help&&<p>Login: gunakan email contoh dan password bebas. Reset: masukkan email, lalu tekan OK di konfirmasi untuk membuka form password baru. Email tidak dikirim. Password baru berlaku selama halaman ini belum dimuat ulang.</p>}</div></>
}
