"use client";
import {useEffect,useState,type FormEvent} from "react";
import {MamsShell} from "./dashboard";
import {Input} from "./ui/input";
import {Button} from "./ui/button";
import {toast} from "sonner";

type ProfileData={name:string;email:string;phone:string};
const defaults:ProfileData={name:"John Doe",email:"john.doe@example.com",phone:""};
export function Profile({onLogout,onDashboard,onRegister}:{onLogout:()=>void;onDashboard:()=>void;onRegister:()=>void}){
  const [saved,setSaved]=useState(defaults),[draft,setDraft]=useState(defaults),[ready,setReady]=useState(false);
  useEffect(()=>{try{const email=sessionStorage.getItem("mams-login-email")||localStorage.getItem("mams-remembered-email")||defaults.email;const raw=sessionStorage.getItem("mams-profile");const data=raw?JSON.parse(raw):{};const initial={name:typeof data.name==="string"?data.name:defaults.name,email,phone:typeof data.phone==="string"?data.phone:""};setSaved(initial);setDraft(initial)}catch{}setReady(true)},[]);
  function save(event:FormEvent){event.preventDefault();const data={...draft,name:draft.name.trim(),phone:draft.phone.trim()};if(!data.name){toast.error("Nama lengkap wajib diisi.");return}try{sessionStorage.setItem("mams-profile",JSON.stringify(data));setSaved(data);setDraft(data);window.dispatchEvent(new Event("mams-profile-updated"));toast.success("Profil berhasil diperbarui.")}catch{toast.error("Profil belum tersimpan. Penyimpanan browser tidak tersedia.")}}
  return <MamsShell title="Profile" active="Profile" profileName={saved.name} onLogout={onLogout} onDashboard={onDashboard} onRegister={onRegister}><main className="reg-content mams-profile-page"><section className="reg-card mams-profile-overview"><img src="/assets/dashboard/imgImage.png" width={72} height={72} alt="Foto profil pengguna demo"/><div><span className="mams-profile-caption">AKUN MAMS</span><h2>{saved.name}</h2><p>{saved.email}</p><span className="mams-profile-status">Pengguna demo · Aktif</span></div></section><form onSubmit={save}><section className="reg-card"><h2>Informasi Profile</h2><p className="reg-description">Kelola informasi akun yang ditampilkan di MAMS.</p><div className="reg-fields"><div className="reg-field"><label htmlFor="profile-name">Nama Lengkap <span className="reg-required">*</span></label><div className="reg-input"><Input id="profile-name" value={draft.name} required maxLength={80} autoComplete="name" disabled={!ready} onChange={e=>setDraft({...draft,name:e.target.value})}/></div></div><div className="reg-field"><label htmlFor="profile-email">Email</label><div className="reg-input reg-locked"><Input id="profile-email" type="email" value={saved.email} readOnly/></div><p className="mams-profile-note">Email mengikuti akun yang digunakan untuk login.</p></div><div className="reg-field"><label htmlFor="profile-phone">Nomor Telepon <span className="mams-profile-optional">(Opsional)</span></label><div className="reg-input"><Input id="profile-phone" type="tel" autoComplete="tel" maxLength={24} placeholder="Contoh: +62 812 3456 7890" value={draft.phone} disabled={!ready} onChange={e=>setDraft({...draft,phone:e.target.value})}/></div></div><div className="reg-field"><label htmlFor="profile-role">Role</label><div className="reg-input reg-locked"><Input id="profile-role" readOnly value="Operasional (demo)"/></div><p className="mams-profile-note">Hak akses akun ditentukan oleh administrator.</p></div></div><p className="mams-profile-demo">Perubahan profil disimpan di browser selama sesi demo ini.</p></section><div className="reg-actions"><Button variant="outline" type="button" className="reg-outline" disabled={!ready} onClick={()=>setDraft(saved)}>Batal</Button><Button type="submit" className="reg-primary" disabled={!ready}>Simpan Perubahan</Button></div></form></main></MamsShell>;
}
