"use client";
import {useState,useReducer,useRef,useEffect,type Dispatch,type FormEvent,type ReactNode} from "react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Checkbox} from "@/components/ui/checkbox";
import {RadioGroup,RadioGroupItem} from "@/components/ui/radio-group";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {MamsShell} from "@/components/dashboard";
import {toast} from "sonner";
import {NEW_NPWP,COMPANY_NPWP,PERSONAL_NPWP,channelNames,merchantFields,ownerFields,companyFields,agencyFields,agencyMore,agencyPic,edcFields,documentLabels,makeRegistration,registrationReducer,type Field,type RegistrationState,type RegistrationAction,type DocumentItem} from "@/lib/registration";
const assets="/assets/registration/";
type FormProps={state:RegistrationState;dispatch:Dispatch<RegistrationAction>;review?:boolean};
function Asset({name,width=20,height=width}:{name:string;width?:number;height?:number}){return <img src={`${assets}${name}.svg`} width={width} height={height} style={{width,height}} alt=""/>}
export function FieldInput({field,state,dispatch,review=false}:{field:Field}&FormProps){const id=`reg-${field.key}`,value=field.key==="agencyOutlet"?state.data.merchant:field.key==="agencyAddress"?state.data.address:state.data[field.key]??"";const locked=review||field.readOnly||(state.result!=="new"&&(ownerFields.includes(field)||companyFields.includes(field)));return <div className="reg-field"><label htmlFor={id}>{field.label}{field.required&&<span className="reg-required"> *</span>}</label><div className={`reg-input ${locked?"reg-locked":""} ${field.options?"reg-select":""}`}>
{field.phone&&<div className="reg-country"><Asset name="flag"/><span>+62</span><Asset name="chevron"/></div>}
{field.options&&!locked?<><select id={id} value={value} required={field.required} onChange={e=>dispatch({type:"FIELD",key:field.key,value:e.target.value})}>{field.options.map(v=><option key={v} value={v}>{v}</option>)}</select><Asset name="chevron"/></>:<Input id={id} value={value} readOnly={locked} required={field.required} type={field.type??(field.phone?"tel":"text")} min={field.type==="number"?1:undefined} placeholder={field.phone?"Masukan Nomor Telepon":""} onChange={e=>dispatch({type:"FIELD",key:field.key,value:e.target.value})}/>}
</div></div>}
export function Fields({fields,...props}:{fields:Field[]}&FormProps){return <div className="reg-fields">{fields.map(f=><FieldInput key={f.key} field={f} {...props}/>)}</div>}
function Choices({label,name,choices,...p}:{label:string;name:string;choices:string[]}&FormProps){return <div className="reg-choice"><p>{label}</p><RadioGroup className="reg-radio-row" value={p.state.data[name]} onValueChange={v=>p.dispatch({type:"FIELD",key:name,value:v})} disabled={p.review}>{choices.map(c=><label className="reg-radio-label" key={c} htmlFor={`reg-${name}-${c}`}><RadioGroupItem id={`reg-${name}-${c}`} value={c}/><span>{c}</span></label>)}</RadioGroup></div>}
function Tick({label,name,...p}:{label:string;name:string}&FormProps){const checked=!!p.state.checks[name];return <label className="reg-tick" htmlFor={`reg-tick-${name}`}><span className="reg-checkbox-slot"><Checkbox id={`reg-tick-${name}`} checked={checked} disabled={p.review} onCheckedChange={()=>p.dispatch({type:"TOGGLE",key:name})}/>{checked&&<span className="reg-checkbox-art"><Asset name="checked"/></span>}</span><span>{label}</span></label>}
function SectionTitle({children}:{children:ReactNode}){return <h3 className="reg-section-title">{children}</h3>}
function Upload({name,label,value,dispatch,review=false,max=50*1024*1024}:{name:string;label:string;value?:DocumentItem;dispatch:Dispatch<RegistrationAction>;review?:boolean;max?:number}){const input=useRef<HTMLInputElement>(null);function choose(file?:File){if(!file)return;const extension=file.name.split('.').pop()?.toLowerCase();if(!["jpg","jpeg","png","pdf","mp4"].includes(extension??"")){toast.error("Format tidak didukung",{description:"Gunakan JPEG, PNG, PDF, atau MP4."});return}if(file.size>max){toast.error(`Ukuran file maksimal ${Math.round(max/1024/1024)} MB`);return}const url=URL.createObjectURL(file);dispatch({type:"DOCUMENT",key:name,value:{name:file.name,size:file.size,url}})}return <div className="reg-upload"><p>{label}</p><input ref={input} className="sr-only" type="file" aria-label={label} accept=".jpg,.jpeg,.png,.pdf,.mp4" onChange={e=>choose(e.target.files?.[0])}/>{value?<><div className="reg-file"><div className="reg-file-thumb">{value.url&&(value.sample||/\.(png|jpe?g)$/i.test(value.name))?<img src={value.url} width={52} height={52} alt="Pratinjau dokumen"/>:<span>FILE</span>}</div><div className="reg-file-copy"><div><p>{value.name}</p><Asset name="upload-check"/></div><div className="reg-progress"><span/></div><div className="reg-file-meta"><span>{Math.round(value.size/1000)}kb</span><span>100%</span></div></div>{!review&&<button type="button" className="reg-file-remove" aria-label={`Hapus ${label}`} onClick={()=>dispatch({type:"DOCUMENT",key:name,value:null})}><Asset name="trash" width={24}/></button>}</div><div className="reg-file-meta"><span>Supported format : png, jpeg, pdf</span><span>Max file size : {Math.round(max/1024/1024)}mb</span></div></>:review?<p className="reg-no-file">Belum ada dokumen</p>:<div className="reg-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><div><strong>Choose a file or drag &amp; drop it here</strong><p>JPEG, PNG, PDF, and MP4 formats, up to {Math.round(max/1024/1024)}MB</p></div><Button variant="outline" type="button" onClick={()=>input.current?.click()}>Browse File</Button></div>}</div>}
function MerchantInfo(p:FormProps){const {state:s,dispatch:d,review}=p;return <>
<SectionTitle>A. Data Merchant</SectionTitle><div className="reg-fields"><Choices label="Tipe Merchant" name="merchantType" choices={["Perorangan","Badan Usaha"]} {...p} review={review||s.result!=="new"}/><Fields fields={merchantFields} {...p}/></div>
<SectionTitle>B. Data Penanggung Jawab Usaha</SectionTitle><div className="reg-fields">{s.result==="new"&&<Upload name="ownerKtp" label="Upload KTP Pemilik Usaha" value={s.docs.ownerKtp} dispatch={d} review={review}/>}<Fields fields={ownerFields} {...p}/></div>
{s.data.merchantType==="Badan Usaha"&&<><SectionTitle>C. Data Perusahaan</SectionTitle><div className="reg-fields">{s.result==="new"&&<Upload name="companyTax" label="Upload NPWP Perusahaan" value={s.docs.companyTax} dispatch={d} review={review}/>}<Fields fields={companyFields} {...p}/></div></>}
<SectionTitle>{s.data.merchantType==="Badan Usaha"?"D":"C"}. Settlement</SectionTitle><div className="reg-fields"><div className="reg-account-row"><FieldInput field={{key:"account",label:"Nomor Rekening"}} {...p}/>{!review&&<><Button variant="outline" className="reg-outline" type="button" onClick={()=>{d({type:"FIELD",key:"account",value:""});d({type:"ACCOUNT",checked:false})}}>Reset</Button><Button className="reg-primary" type="button" disabled={s.accountChecked} onClick={()=>/^\d{6,20}$/.test(s.data.account)?d({type:"ACCOUNT",checked:true}):d({type:"ERROR",value:"Masukkan nomor rekening berisi 6–20 digit."})}>Periksa</Button></>}</div>{s.accountChecked&&<p className="reg-account-status"><Asset name="account-check"/>Terdaftar</p>}<Fields fields={[{key:"accountOwner",label:"Nama Pemilik rekening",readOnly:true},{key:"bank",label:"Nama Bank",readOnly:true}]} {...p}/></div>
</>}
export function ChannelInfo(p:FormProps){const {state:s,dispatch:d,review}=p;const qris=s.channels.includes("QRIS"),va=s.channels.includes("Virtual Account"),agency=s.channels.includes("Keagenan/Mini ATM"),card=s.channels.includes("Card Payment");return <>
<SectionTitle>A. Channel Payment</SectionTitle><div className="reg-channel-grid">{channelNames.map(c=>{const checked=s.channels.includes(c);return <label key={c} className={`reg-channel-card ${checked?"selected":""} ${review?"reg-review-channel":""}`}><div><span className="reg-channel-icon"><Asset name="channel" width={24}/></span><span className="reg-checkbox-slot"><Checkbox checked={checked} disabled={review} aria-label={c} onCheckedChange={()=>d({type:"CHANNEL",value:c})}/>{checked&&<span className="reg-checkbox-art"><Asset name="checked"/></span>}</span></div><strong>{c}</strong><p>Terima Pembayaran QRIS dari semua aplikasi e-wallet &amp; m-banking</p></label>})}</div>
{qris&&<><SectionTitle>B. QRIS</SectionTitle><div className="reg-fields"><Choices label="Apakah di lokasi yang anda daftarkan, sudah terdapat QRIS dari institusi / bank lain ?" name="existingQris" choices={["Iya, Sudah Terdaftar","Tidak, Belum Terdaftar"]} {...p}/>{s.data.existingQris==="Iya, Sudah Terdaftar"&&<FieldInput field={{key:"nmid",label:"NMID",required:true}} {...p}/>}<Choices label="Tipe QRIS" name="qrisType" choices={["Statis","Dinamis"]} {...p}/><Fields fields={[{key:"merchant",label:"QRIS Outlet",readOnly:true},{key:"settlement",label:"Settlement Account",readOnly:true}]} {...p}/></div></>}
{va&&<><SectionTitle>C. Virtual Account Configuration</SectionTitle><div className="reg-fields"><FieldInput field={{key:"settlement",label:"Settlement Account",readOnly:true}} {...p}/><div className="reg-choice"><p>VA Type</p><div className="reg-tick-row"><Tick name="vaStatic" label="Statis" {...p}/><Tick name="vaDynamic" label="Dinamis" {...p}/></div></div><Fields fields={[{key:"vaPrefix",label:"Prefix/Identifier",options:["Assigned automatically after approval","Custom prefix"]},{key:"callback",label:"Callback URL",type:"url"},{key:"vaEmail",label:"Notifikasi Email",type:"email"}]} {...p}/></div></>}
{card&&<SectionTitle>D. Card Payment</SectionTitle>}
{agency&&<><SectionTitle>E. Keagenan/Mini ATM</SectionTitle><div className="reg-fields"><Fields fields={agencyFields} {...p}/><Choices label="Sudah Menjadi Agen Bank Lain?" name="agent" choices={["Iya, Sudah Terdaftar","Tidak, Belum Terdaftar"]} {...p}/><Fields fields={agencyMore} {...p}/><div className="reg-choice"><p>Layanan yang Diajukan</p><div className="reg-tick-row">{["Setor tunai","tarik tunai","transfer","pembayaran","top-up"].map((x,i)=><Tick key={x} label={x} name={`service${i}`} {...p}/>)}</div></div><div className="reg-choice"><p>Kanal Operasional</p><div className="reg-tick-row"><Tick label="Aplikasi mobile" name="opMobile" {...p}/><Tick label="Mini ATM–EDC" name="opEdc" {...p}/></div></div><Fields fields={agencyPic} {...p}/><Choices label="Apakah ada kebutuhan EDC ?" name="needsEdc" choices={["Iya, Butuh EDC","Tidak, Butuh EDC"]} {...p}/></div></>}
{(card||(agency&&s.data.needsEdc==="Iya, Butuh EDC"))&&<><SectionTitle>F. Info EDC</SectionTitle><div className="reg-fields"><FieldInput field={edcFields[0]} {...p} state={{...s,data:{...s.data,installation:s.checks.sameAddress?s.data.address:s.data.installation}}} review={review||s.checks.sameAddress}/><Tick label="Sama Seperti Alamat merchant" name="sameAddress" {...p}/><Fields fields={edcFields.slice(1)} {...p}/></div></>}
</>}
function Documents(p:FormProps){return <>{["A. Dokumen Merchant","B. Dokumen lokasi/Outlet","C. Dokumen tambahan keagenan"].map((title,i)=>{if(i===2&&!p.state.channels.includes("Keagenan/Mini ATM"))return null;const range=i===0?[0,1]:i===1?[2,3,4]:[5,6];return <div key={title} className="reg-doc-section"><SectionTitle>{title}</SectionTitle><div className="reg-fields">{range.map(j=><Upload key={j} name={`doc${j}`} label={documentLabels[j]} value={p.state.docs[`doc${j}`]} dispatch={p.dispatch} review={p.review} max={j<2?50*1024*1024:1024*1024}/>)}</div></div>})}</>}
const stages=[{title:"Info Merchant",description:"Informasi Data Merchant"},{title:"Pilih Channel",description:"Informasi Data Merchant"},{title:"Dokumen",description:"Upload Dokumen Pendukung"},{title:"Konfirmasi Ulang",description:"Konfirmasi Ulang Data"}];
export function RegistrationForm({initialState}:{initialState?:RegistrationState}){const [state,dispatch]=useReducer(registrationReducer,initialState??makeRegistration());const form=useRef<HTMLFormElement>(null);const previewUrls=useRef(new Set<string>());const s=state;const [motion,setMotion]=useState({step:s.step,direction:"forward"});if(motion.step!==s.step)setMotion({step:s.step,direction:s.step<motion.step?"back":"forward"});
useEffect(()=>{Object.values(s.docs).forEach(doc=>{if(doc.url?.startsWith("blob:"))previewUrls.current.add(doc.url)})},[s.docs]);
useEffect(()=>{const urls=previewUrls.current;return()=>urls.forEach(url=>URL.revokeObjectURL(url))},[]);
useEffect(()=>{if(initialState)return;try{const raw=sessionStorage.getItem("mams-registration-draft");if(raw){const draft=JSON.parse(raw);if(draft.data&&Array.isArray(draft.channels)&&draft.docs&&draft.step>=1&&draft.step<=4){dispatch({type:"RESTORE",value:draft});toast.info("Draft registrasi dimuat kembali.")}}}catch{}},[initialState]);
function saveDraft(){try{const docs=Object.fromEntries(Object.entries(s.docs).map(([key,doc])=>[key,{...doc,url:doc.sample?doc.url:undefined}]));sessionStorage.setItem("mams-registration-draft",JSON.stringify({...s,docs,success:false}));toast.success("Draft tersimpan di browser untuk sesi demo ini.")}catch{toast.error("Draft tidak dapat disimpan di browser ini.")}}
const props={state:s,dispatch};useEffect(()=>{window.scrollTo({top:0,behavior:"instant"})},[s.step]);function finish(){try{sessionStorage.removeItem("mams-registration-draft")}catch{}previewUrls.current.forEach(url=>URL.revokeObjectURL(url));previewUrls.current.clear();dispatch({type:"RESET"})}function submit(e:FormEvent){e.preventDefault();if(s.step===0){dispatch({type:"CHECK"});return}if(s.step===1&&!s.accountChecked){dispatch({type:"ERROR",value:"Periksa nomor rekening settlement sebelum melanjutkan."});return}if(s.step===2&&!s.channels.length){dispatch({type:"ERROR",value:"Pilih minimal satu channel pembayaran."});return}if(s.step===2&&s.channels.includes("Virtual Account")&&!s.checks.vaStatic&&!s.checks.vaDynamic){dispatch({type:"ERROR",value:"Pilih minimal satu VA Type."});return}if(s.step===4)dispatch({type:"SEND"});else dispatch({type:"STEP",step:s.step+1})}
return <main className="reg-content"><form key={s.step} ref={form} className="mams-form-step" data-motion-direction={motion.direction} onSubmit={submit} noValidate={s.step===4}>
{s.step===0?<><section className="reg-card reg-lookup"><Tabs value="registration" onValueChange={()=>toast.info("Bulk Upload belum termasuk demo registrasi ini.")}><TabsList className="reg-tabs"><TabsTrigger value="registration">Registrasi Merchant</TabsTrigger><TabsTrigger value="bulk">Bulk Upload</TabsTrigger></TabsList></Tabs><h2>Registrasi Merchant</h2><p className="reg-description">Description of the capacity of this feature or page, so that users know what its functionality is.</p><div className="reg-npwp-row"><div className="reg-field"><label htmlFor="reg-npwp">NPWP</label><Input id="reg-npwp" value={s.npwp} inputMode="numeric" required readOnly={!!s.result} placeholder={NEW_NPWP} onChange={e=>dispatch({type:"NPWP",value:e.target.value})}/></div>{s.result&&<Button className="reg-outline" variant="outline" type="button" onClick={()=>dispatch({type:"RESET"})}>Reset</Button>}<Button className="reg-primary" type="submit" disabled={!!s.result}>Periksa</Button></div>
{s.result&&<div className="reg-npwp-result" role="status"><Asset name={s.result==="new"?"status-new":"status-existing"} width={75}/><strong>{s.result==="new"?"NPWP Belum Terdaftar":"NPWP Sudah Terdaftar"}</strong><p>{s.result==="new"?"Merchant dapat didaftarkan sebagai merchant baru":"Dengan data berikut, tambah outlet baru ?"}</p></div>}
{s.result&&s.result!=="new"&&<><SectionTitle>{s.result==="company"?"Data Perusahaan":"Data Pemilik Usaha"}</SectionTitle><Fields fields={s.result==="company"?companyFields:ownerFields} {...props} state={{...s,data:{...s.data,companyNpwp:s.npwp,companyPhone:"88-8880-8885",ownerMobile:"1255-4545-5555"}}} review/></>}
</section>{s.error&&<p className="reg-error" role="alert">{s.error}</p>}{s.result&&<div className="reg-actions"><Button type="button" className="reg-primary" onClick={()=>dispatch({type:"START"})}>{s.result==="new"?"Proses":"Tambah Outlet"}</Button></div>}
<details className="reg-demo"><summary>Mode demo · Contoh NPWP</summary><p>Pengecekan menggunakan data contoh. Pilih NPWP untuk mencoba alurnya:</p><div><button type="button" onClick={()=>dispatch({type:"NPWP",value:NEW_NPWP})}>Belum terdaftar: {NEW_NPWP}</button><button type="button" onClick={()=>dispatch({type:"NPWP",value:COMPANY_NPWP})}>Terdaftar — perusahaan: {COMPANY_NPWP}</button><button type="button" onClick={()=>dispatch({type:"NPWP",value:PERSONAL_NPWP})}>Terdaftar — perorangan: {PERSONAL_NPWP}</button></div></details></>:<>
<div className="reg-breadcrumb"><button type="button" onClick={()=>dispatch({type:"STEP",step:0})}>Registrasi Merchant</button><span>/</span><strong>{s.result==="new"?"Merchant Baru":"Tambah Outlet"}</strong></div><section className="reg-card reg-stepper" aria-label="Tahapan registrasi">{stages.map((stage,i)=><div className={`reg-step ${s.step>=i+1?"done":""}`} key={stage.title} aria-current={s.step===i+1?"step":undefined}><span className="reg-step-line"/><span className="reg-step-status">{s.step>=i+1?<Asset name="step-check"/>:i+1}</span><strong>{stage.title}</strong><p>{stage.description}</p></div>)}</section>
<section className="reg-card reg-form-card"><h2>{s.step}. {stages[s.step-1].title}</h2><p className="reg-description">{s.step===4?"Periksa kembali data merchant, channel, dan dokumen sebelum dikirim.":"Description of the capacity of this feature or page, so that users know what its functionality is."}</p>{s.step===1?<MerchantInfo {...props}/>:s.step===2?<ChannelInfo {...props}/>:s.step===3?<Documents {...props}/>:<><MerchantInfo {...props} review/><div className="reg-review-heading"><h2>Channel Pembayaran</h2><Button type="button" variant="outline" className="reg-outline" onClick={()=>dispatch({type:"STEP",step:2})}>Ubah Channel</Button></div><ChannelInfo {...props} review/><div className="reg-review-heading"><h2>Dokumen Pendukung</h2><Button type="button" variant="outline" className="reg-outline" onClick={()=>dispatch({type:"STEP",step:3})}>Ubah Dokumen</Button></div><Documents {...props} review/></>}</section>
{s.error&&<p className="reg-error" role="alert">{s.error}</p>}<div className="reg-actions"><Button type="button" variant="outline" className="reg-outline" onClick={()=>dispatch({type:"STEP",step:s.step-1})}>Back</Button>{(s.step===1||s.step===4)&&<Button type="button" variant="outline" className="reg-outline" onClick={saveDraft}>Simpan Draft</Button>}<Button type="submit" className="reg-primary">{s.step===4?"Send":"Next"}</Button></div></>}
</form><footer className="dash-footer">Powered By PT.Solusi Pembayaran Elektronik</footer><Dialog open={s.success} onOpenChange={open=>{if(!open)finish()}}><DialogContent className="reg-success mams-success" showCloseButton={false}><Asset name="status-new" width={75}/><DialogTitle>Registrasi Merchant Berhasil</DialogTitle><DialogDescription>{s.result==="new"?"Pengajuan merchant baru":"Pengajuan outlet baru"} berhasil dikirim.</DialogDescription><Button className="reg-primary" onClick={finish}>OK</Button></DialogContent></Dialog></main>}
export function MerchantRegistration({onLogout,onDashboard}:{onLogout:()=>void;onDashboard:()=>void}){return <MamsShell title="Register Merchant" active="Registrasi Merchant" onLogout={onLogout} onDashboard={onDashboard} onRegister={()=>window.scrollTo({top:0,behavior:"smooth"})}><RegistrationForm/></MamsShell>}
